defaults:
  - _seg_default

net:
  _target_: src.models.components.dofa.DOFA
  pretrained: True
  pretrained_path: datasets/Models/DOFA_ViT_base_e100.pth
  wavelengths: [0.660, 0.560, 0.490, 0.825]
  segmentation_head:
    _partial_: True
    _target_: src.models.components.utils.SimpleSegmentationHead
    decoder_stride: 16
