defaults:
  - _seg_default

net:
  _target_: src.models.components.satlas.Satlas
  pretrained: True
  pretrained_path: datasets/init_models/SatLas_aerial_swinb_si.pth
  use_FPN: False
  segmentation_head:
    _partial_: True
    _target_: src.models.components.utils.SimpleSegmentationHead
    decoder_stride: 32
