defaults:
  - ViT_S

net:
  ViT_patch_size: 16
  ViT_embed_dim: 1024
  ViT_depth: 24
  ViT_num_heads: 16
  ViT_mlp_ratio: 4.0
  pretrained_encoder_path: datasets/Models/deit_3_large_224_21k.pth #patchsize 16
