resolution: 1.5 # resolution at which to compute change, use bilinear interpolation on input images to match resolution if necessary
delta_list: [-5, -10, -15, -20] # minimum change in height (in meters)
min_area_list: [10, 25, 100, 200, 300, 400] # minimum area of a contiguous change of more than delta (in square meters)
classes_to_keep: [1, 2, 3, 4, 5, 6] # classes on which to compute change metrics, based on the lidar classification raster (cf. https://geoservices.ign.fr/sites/default/files/2023-10/DC_LiDAR_HD_1-0_PTS.pdf)

delta_fig: -10 # minimum change in height (in meters) used for plots
min_area_fig: 100 # minimum area of a contiguous change of more than delta (in square meters) used for plots

root_dir: ./ # root dir for relative paths
extract_tif: true # extract a tif image from predictions with the same bounds as labels from which the mask is computed, and also extract masked images from labels to mask on

year_1: 2022
year_2: 2023

labels_1:
  path: datasets/canopy_height_change/lidar_1.tif
  unit: dm # m(meter), dm(decimeter), cm(centimeter)
  crs: 2154
  mask_on: false

labels_2:
  path: datasets/canopy_height_change/lidar_2.tif
  unit: m # m(meter), dm(decimeter), cm(centimeter)
  crs: 2154
  mask_on: true

classification:
  year: 2022
  path: datasets/canopy_height_change/lidar_classification.tif
  crs: 2154

predictions_1:
  path: datasets/canopy_height_change/predictions_1.tif
  unit: dm # m(meter), dm(decimeter), cm(centimeter)
  crs: 2154

predictions_2:
  path: datasets/canopy_height_change/predictions_2.tif
  unit: dm # m(meter), dm(decimeter), cm(centimeter)
  crs: 2154

inputs_1:
  path: datasets/canopy_height_change/spot_1.tif
  crs: 2154

inputs_2:
  path: datasets/canopy_height_change/spot_2.tif
  crs: 2154

save_dir: change_metrics