# @package _global_

defaults:
  - _self_
  - data: canopy # choose datamodule with `test_dataloader()` for evaluation
  - model: _seg_default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - //lustre/fswork/projects/rech/ego/commun/fajwel/models/3__PVTv2_B/.hydra/config.yaml

tags: ["dev"]
